---
title: "class"
author: "Morgan Booker"
date: "11/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(googlesheets4)
```

```{r}

sheets_deauth()
x <- read_sheet("13NhlT-Oik5P4NOKRWwrJ7xZQlddFNk81HHEw9wkWglM")
x

#partisanship dvote

x %>% 
  ggplot(aes(x = partisanship)) +
  geom_histogram(binwidth = .5, color = "white") +
  facet_wrap(~dvote)

x %>%
  mutate(dvote = as.factor(dvote)) %>% 
  ggplot(aes(x = partisanship, y = dvote, color = dvote)) +
  geom_jitter(height = .1) +
  geom_smooth(method = "lm", se = FALSE, color = "purple")

x %>%
  ggplot(aes(x = partisanship, y = dvote, color = dvote)) +
  geom_jitter(height = .1) +
  geom_smooth(method = "lm", se = FALSE, color = "purple")

summary(x)

x2 <- x %>%
  mutate(dvote = as.factor(dvote))
   
lm(dvote ~ partisanship, data = x)      
lm(dvote ~ partisanship, data = x2)

glm(dvote ~ partisanship, data = x, family = binomial)

x %>%
  ggplot(aes(x = partisanship, y = dvote, color = dvote)) +
  geom_jitter(height = .1) +
  geom_smooth(method = "glm", se = FALSE, color = "black", method.args = list(family = "binomial"))
```

